# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-04-04 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='propos_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Proposal Date'),
        ),
    ]
