# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-04-04 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0002_student_propos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='propos_date',
            field=models.CharField(max_length=30, null=True, verbose_name=b'Proposal Date'),
        ),
    ]
