# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-01 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0004_auto_20200501_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advising_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name=b'Note Date')),
                ('first_name', models.CharField(max_length=127, verbose_name=b'First Name')),
                ('middle_name', models.CharField(blank=True, max_length=127, verbose_name=b'Middle Name')),
                ('last_name', models.CharField(max_length=127, verbose_name=b'Last Name')),
                ('note', models.CharField(blank=True, max_length=4096, verbose_name=b'Note')),
            ],
            options={
                'verbose_name': 'Advising Note',
            },
        ),
    ]
