# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-05-02 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0005_advising_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advising_note',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='advising_note',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='advising_note',
            name='first_name',
            field=models.CharField(blank=True, max_length=127, verbose_name=b'First Name'),
        ),
        migrations.AlterField(
            model_name='advising_note',
            name='last_name',
            field=models.CharField(blank=True, max_length=127, verbose_name=b'Last Name'),
        ),
    ]
